// <auto-generated />
using System;
using ColdStorageManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coldstorage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251219151849_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ColdStorageManagement.Models.ColdRoom", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("StorageType")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalCapacity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UsedCapacity")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomName")
                        .IsUnique();

                    b.ToTable("ColdRooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            CreatedDate = new DateTime(2025, 12, 19, 21, 18, 48, 795, DateTimeKind.Local).AddTicks(596),
                            Description = "Ultra-low temperature for frozen goods",
                            RoomName = "Freezer Room A",
                            Status = "Operational",
                            StorageType = "Frozen",
                            Temperature = -20.0m,
                            TotalCapacity = 5000.0m,
                            UsedCapacity = 1500.0m
                        },
                        new
                        {
                            RoomId = 2,
                            CreatedDate = new DateTime(2025, 12, 19, 21, 18, 48, 795, DateTimeKind.Local).AddTicks(599),
                            Description = "Medium temperature for dairy and vegetables",
                            RoomName = "Chilled Room B",
                            Status = "Operational",
                            StorageType = "Chilled",
                            Temperature = 2.0m,
                            TotalCapacity = 3000.0m,
                            UsedCapacity = 800.0m
                        },
                        new
                        {
                            RoomId = 3,
                            CreatedDate = new DateTime(2025, 12, 19, 21, 18, 48, 795, DateTimeKind.Local).AddTicks(601),
                            Description = "Room temperature for non-perishables",
                            RoomName = "Ambient Room C",
                            Status = "Operational",
                            StorageType = "Ambient",
                            Temperature = 18.0m,
                            TotalCapacity = 8000.0m,
                            UsedCapacity = 2000.0m
                        });
                });

            modelBuilder.Entity("ColdStorageManagement.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PricePerDay")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ProductId");

                    b.HasIndex("ExpiryDate");

                    b.HasIndex("ProductName");

                    b.HasIndex("RoomId");

                    b.HasIndex("Status");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Meat",
                            EntryDate = new DateTime(2025, 12, 9, 21, 18, 48, 795, DateTimeKind.Local).AddTicks(638),
                            ExpiryDate = new DateTime(2026, 6, 19, 21, 18, 48, 795, DateTimeKind.Local).AddTicks(621),
                            Notes = "Premium quality",
                            PricePerDay = 10.0m,
                            ProductName = "Frozen Beef",
                            Quantity = 500.0m,
                            RoomId = 1,
                            Status = "Active"
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Dairy",
                            EntryDate = new DateTime(2025, 12, 17, 21, 18, 48, 795, DateTimeKind.Local).AddTicks(646),
                            ExpiryDate = new DateTime(2025, 12, 24, 21, 18, 48, 795, DateTimeKind.Local).AddTicks(645),
                            Notes = "Pasteurized",
                            PricePerDay = 6.0m,
                            ProductName = "Fresh Milk",
                            Quantity = 300.0m,
                            RoomId = 2,
                            Status = "Active"
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Fruits",
                            EntryDate = new DateTime(2025, 12, 14, 21, 18, 48, 795, DateTimeKind.Local).AddTicks(649),
                            ExpiryDate = new DateTime(2026, 1, 2, 21, 18, 48, 795, DateTimeKind.Local).AddTicks(647),
                            Notes = "Fresh from orchard",
                            PricePerDay = 5.0m,
                            ProductName = "Apples",
                            Quantity = 800.0m,
                            RoomId = 3,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("ColdStorageManagement.Models.StockTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("PerformedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("Date");

                    b.HasIndex("ProductId");

                    b.ToTable("StockTransactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            Date = new DateTime(2025, 12, 9, 21, 18, 48, 795, DateTimeKind.Local).AddTicks(699),
                            Notes = "Initial stock",
                            PerformedBy = "admin",
                            ProductId = 1,
                            Quantity = 500.0m,
                            ReferenceNumber = "IN-001",
                            Type = 0
                        },
                        new
                        {
                            TransactionId = 2,
                            Date = new DateTime(2025, 12, 17, 21, 18, 48, 795, DateTimeKind.Local).AddTicks(702),
                            Notes = "Daily delivery",
                            PerformedBy = "staff",
                            ProductId = 2,
                            Quantity = 300.0m,
                            ReferenceNumber = "IN-002",
                            Type = 0
                        });
                });

            modelBuilder.Entity("ColdStorageManagement.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedDate = new DateTime(2025, 12, 19, 21, 18, 48, 795, DateTimeKind.Local).AddTicks(476),
                            Email = "admin@coldstorage.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            Password = "admin123",
                            Phone = "01712345678",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedDate = new DateTime(2025, 12, 19, 21, 18, 48, 795, DateTimeKind.Local).AddTicks(478),
                            Email = "staff@coldstorage.com",
                            FullName = "Storage Staff",
                            IsActive = true,
                            Password = "staff123",
                            Phone = "01787654321",
                            Role = "Staff",
                            Username = "staff"
                        });
                });

            modelBuilder.Entity("ColdStorageManagement.Models.Product", b =>
                {
                    b.HasOne("ColdStorageManagement.Models.ColdRoom", "ColdRoom")
                        .WithMany("Products")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ColdRoom");
                });

            modelBuilder.Entity("ColdStorageManagement.Models.StockTransaction", b =>
                {
                    b.HasOne("ColdStorageManagement.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ColdStorageManagement.Models.ColdRoom", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
